name: Lab Task
description: Track a single lab deliverable from plan to done
title: "[LAB] <short title>"
labels: ["lab"]
assignees: []
body:
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What will this lab prove/show?
  - type: textarea
    id: plan
    attributes:
      label: Plan
      description: Tools, data, and steps
      placeholder: |
        - Tools:
        - Data:
        - Steps:
  - type: textarea
    id: artifacts
    attributes:
      label: Artifacts to Produce
      description: README with screenshots, queries/rules, scripts, etc.
  - type: textarea
    id: results
    attributes:
      label: Results & Findings
      description: Summary + IOCs if applicable
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: Repo scaffolded
        - label: Data collected (safe/sanitized)
        - label: Analysis completed
        - label: Write-up complete
        - label: Linked back to roadmap README
